
services:
  - type: web
    name: tiktok-quiz-server
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3001
      - key: CORS_ORIGIN
        sync: false
      - key: ADMIN_TOKEN
        sync: false
      - key: TIKTOK_LIVE_USERNAME
        sync: false
      - key: TIKTOK_CLIENT_KEY
        sync: false
      - key: TIKTOK_CLIENT_SECRET
        sync: false
      - key: TIKTOK_REDIRECT_URI
        sync: false
